export const stockItems = [

    /*{ name: 'test', fixedStock: '10 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'testthai' },
    { name: 'test1', fixedStock: '10 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'testthai' },
    { name: 'test2', fixedStock: '10 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'testthai' },
    { name: 'test3', fixedStock: '10 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'testthai' },
    { name: 'test4', fixedStock: '10 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'testthai' },
    { name: 'test5', fixedStock: '10 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'testthai' },
    { code: '1460', name: 'J.W.Black Label (700 ml)', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'testbarday' },
    { code: '1489', name: 'Bombay Sapphire Gin 750 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'testbarday' },
    { code: '1461', name: 'Chivas 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'testbarday' },
    { code: '1460', name: 'J.W.Black Label (700 ml)', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'testbarday' },
    { code: '1489', name: 'Bombay Sapphire Gin 750 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'testbarday' },
    { code: '1461', name: 'Chivas 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'testbarday' },
    { code: '1460', name: 'J.W.Black Label (700 ml)', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'testbarday' },
    { code: '1489', name: 'Bombay Sapphire Gin 750 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'testbarday' },
    { code: '1461', name: 'Chivas 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'testbarday' },*/

    // Thai kitchen
 // { name: 'test', fixedStock: '10 กก', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'กุ้ง 20-22 ตัว/กก.', fixedStock: '10', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'กุ้ง 28-30 ตัว/กก.', fixedStock: '10', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'กุ้งเสือ 8 ตัว/กก', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'กุ้งแห้ง', fixedStock: '1', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ไข่ไก่เบอร์ 0', fixedStock: '5', unit: 'แผง', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ไข่เค็ม', fixedStock: '10', unit: 'ฟอง', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ไข่เป็ดเบอร์0', fixedStock: '30', unit: 'ฟอง', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ไข่เยียวม้า', fixedStock: '20', unit: 'ฟอง', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'คอหมู', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ซี่โครงไก่', fixedStock: '1', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'เนื้อวัวบด', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'เนื้อวัวริบอาย ออสเตรีย', fixedStock: '5', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'เนื้อวัวสันนอก', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ปลากระพง 800 กรัม/ตัว', fixedStock: '4', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ปลาทู ขนาดใหญ่', fixedStock: '10', unit: 'ตัว', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ปลาสลิด 9-10ตัว/กก', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ปลาหมึกศอก 2-4 ตัว/กก', fixedStock: '10', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ปีกไก่กลาง', fixedStock: '5', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'สะโพกไก่เลาะกระดูก', fixedStock: '3', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'สะโพกไก่เลาะกระดูกบด', fixedStock: '4', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ไส้กรอกอีสาน ส.ขอนแก่น', fixedStock: '2', unit: 'แพ็ค', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'หมูสะโพก', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'หมูสันใน', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'หมูสับปนมัน 25%', fixedStock: '5', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'ห่อหมก', fixedStock: '15', unit: 'ชิ้น', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'แหนมสด ส.ขอนแก่น', fixedStock: '5', unit: 'แท่ง', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'อกไก่ลอกหนัง', fixedStock: '4', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'เอ็นต์แก้วไก่', fixedStock: '5', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวไทย' },
    { name: 'กระชายหัว', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'กะหล่ำปลี', fixedStock: '2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'กะหล่ำปลีม่วง', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ข้าวโพดอ่อน', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ข่าอ่อน', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ขิงแก่', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'คะน้าฮ่องกงต้นใหญ่', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'คื่นฉ่าย', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ชะอม', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ต้นหอม', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ตะไคร้', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'แตงร้าน ลูกใหญ่', fixedStock: '2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ถั่วฝักยาว', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ใบกระเพรา', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ใบตอง', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ใบเตย', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ใบมะกรูด', fixedStock: '0.2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ใบสะระแหน่', fixedStock: '0.2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ใบโหระพา', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ผักกาดขาว', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ผักชีครัวไทย', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ผักชีฝรั่ง', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'ผักชีลาว', fixedStock: '0.2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'พริกขี้หนูแดงเด็ดก้าน', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'พริกขี้หนูสวนเม็ดเล็ก เขียว', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'พริกชี้ฟ้าแดง', fixedStock: '0.2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'พริกชี้ฟ้าเหลือง', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'พริกครัวไทยอ่อน', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'มะเขือเปาะ', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'มะเขือพวงเด็ดขั้ว', fixedStock: '0.1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'มะนาว', fixedStock: '50', unit: 'ลูก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'มะม่วงดิบ', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'มะละกอดิบ', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'หอมแขก', fixedStock: '3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'หัวใชเท้า', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'เห็ดฟาง', fixedStock: '', unit: '', type: 'ผัก-ผลไม้', kitchen: 'ครัวไทย' },
    { name: 'กระเทียมกลีบเล็ก', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'กระเทียมกลีบใหญ่', fixedStock: '5', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'กะทิอร่อยดี', fixedStock: '4', unit: 'กล่อง', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'กะปิอย่างดี', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'เกร็ดขนมปังฟาร์มเฮ้าส์', fixedStock: '0.5', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'เกลือปรุงทิพย์', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'เกลือเม็ด', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ข้าวหอมมะลิ', fixedStock: '20', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ข้าวเหนียว', fixedStock: '5', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ขิงดองกระปุก', fixedStock: '0.5', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'คนอร์ ผง', fixedStock: '2', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'งาขาว', fixedStock: '0.3', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ซอสปรุงรสฝาเขียว', fixedStock: '2', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ซอสพริกศรีราชา', fixedStock: '2', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ซอสมะเขือเทศ', fixedStock: '2', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ซอสหอยนางรม 3 แม่ครัว', fixedStock: '1', unit: 'กล', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ซีอิ๊วขาวเด็กสมบูรณ์', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ซีอิ๊วดำเด็กสมบูรณ์', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ตั้งฉ่าย', fixedStock: '1', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'เต้าเจี้ยวเด็กสมบูรณ์', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'เต้าหู้ไข่', fixedStock: '5', unit: 'หลอด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ถั่วลิสงดิบ', fixedStock: '3', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'นมข้นจืด', fixedStock: '6', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำกระเทียมดอง', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำจิ้มไก่ แม่ประนอม', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำตาลทรายแดง', fixedStock: '2', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำตาลปิ๊บ', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำปลา', fixedStock: '4', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำปลาร้าแม่บุญล้ำ ฝาเหลือง', fixedStock: '3', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำพริกเผา ฉั่วฮะเส็ง', fixedStock: '1', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำมันงา', fixedStock: '', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำมันปาล์ม', fixedStock: '2', unit: 'ปี๊ป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำมันพริกเผา', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'น้ำส้มสายชู', fixedStock: '2', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'แป้งโกกิ', fixedStock: '2', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'แป้งทอดกรอบ', fixedStock: '2', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ผงลาบ รสดี', fixedStock: '1', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'พริกแกงเขียวหวาน', fixedStock: '0.5', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'พริกแกงคั่วใต้', fixedStock: '0.5', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'พริกแกงเผ็ดหยาบ', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'พริกครัวไทยขาว', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'พริกครัวไทยดำ', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'พริกแห้งเล็ก', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'มะขามเปียก', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'เม็ดมะม่วงหิมพานต์', fixedStock: '3', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'วุ้นเส้น', fixedStock: '1', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'สาหร่าย', fixedStock: '3', unit: 'แผ่น', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'เส้นไวไว', fixedStock: '10', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'เส้นหมีกรอบ', fixedStock: '1', unit: 'แพ็ค', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'หอมเจียว', fixedStock: '0.2', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'เหล้าจีน', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
    { name: 'ข้าวสารพนักงาน', fixedStock: '', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวไทย' },
 
    // Italian Kitchen
    { name: 'CHORIZO CASERO PICANTE (CARCHELEJO) / CJ10', fixedStock: ' ', unit: '', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'SLICE CHORIZO EXTRA (CARCHELEJO) / CJ04', fixedStock: ' ', unit: '', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'SLICE SALAMI EXTRA (CARCHELEJO) / CJ02', fixedStock: ' ', unit: '', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ไข่กุ้งส้ม', fixedStock: '1', unit: 'แพ็ค', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ซาลามี่ ( เปปเปอร์โรนี )', fixedStock: '1', unit: 'แท่ง', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ซี่โครงหมู', fixedStock: '', unit: '', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ดีปลาหมึก', fixedStock: '1', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ตับเป็ด', fixedStock: '1', unit: 'ก้อน', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เนื้อบดครัวไทย', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เนื้อริบอาย ออสเตรีย ตัด 300 กรัม/ชิ้น', fixedStock: '5', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เนื้อริบอาย ออสเตรีย ตัด 600 กรัม/ชิ้น', fixedStock: '5', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เนื้อสันในออสเตรเลีย', fixedStock: '5', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เบคอน', fixedStock: '5', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ปลาเก๋า', fixedStock: '5', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ปลาแซลมอน เทร้า แช่แข็ง', fixedStock: '', unit: '', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ปลาแซลมอน เทร้า สด', fixedStock: '30', unit: 'ชิ้น', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ปลาแซลมอนรมควัน (ราคา/กก.) / ชิ้น', fixedStock: '0.5', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ปลาหิมะ ( ตัว )', fixedStock: '', unit: '', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ปลาหิมะ 200 กรัม/ชิ้น', fixedStock: '7', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ปาร์มาแฮม (เกรด A)', fixedStock: '0.5', unit: 'ขา', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'พ็อคช้อป 300 กรัม/ชิ้น', fixedStock: '10', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'แลมป์แลค (ออสเตรเลีย) ซี่โครงแกละ', fixedStock: '1', unit: 'โครง', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ไส้กรอกไก่คอกเทล', fixedStock: '', unit: '', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ไส้กรอกชีส 6 นิ้ว', fixedStock: '1', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ไส้กรอกสโมค ฟาร์เมอร์', fixedStock: '3', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ไส้กรอกหมูพริกครัวไทยดำ', fixedStock: '1', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ไส้กรอกหมูสด 6 นิ้ว', fixedStock: '1', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'หมูสามชั้น', fixedStock: '3', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'หอยเชลล์', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'หอยแมลงภู่นิวซีแลนด์ (Size L)', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'แอนโชวี่', fixedStock: '0.5', unit: 'ที่', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'แฮม', fixedStock: '2', unit: 'กก', type: 'เนื้อสัตว์', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'สลัดคอส', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'แคนตาลูป ญี่ปุ่น', fixedStock: '1', unit: 'ลูก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'แครอท', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ไควาเรท', fixedStock: '0.2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ดอกกะหล่ำ', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ต้นหอมญี่ปุ่น', fixedStock: '0.2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'แตงกวาญี่ปุ่น', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'แตงซูกินิ', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ถั่วลันเตาญี่ปุ่น', fixedStock: '0.2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ไทม์', fixedStock: '0.01', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'บล็อคโคลี่', fixedStock: '0.3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เบบี้ครอท', fixedStock: '0.2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ผักกาดแก้ว', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ผักโขม', fixedStock: '3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'พริกยักษ์เขียว', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'พริกยักษ์แดง', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'พริกยักษ์เหลือง', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'พลาสลี่', fixedStock: '0.2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เฟร้นฟรายเส้นตรงใหญ่', fixedStock: '5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มะเขือเทศเชอรี่', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มะเขือเทศเชอรี่ติดก้าน', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มะเขือเทศใหญ่', fixedStock: '3', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มันฝรั่ง', fixedStock: '5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มิกซ์สลัด', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ร็อกเก็ต', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ราสเบอร์รี่แช่แข็ง', fixedStock: '', unit: '', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เรดิซ', fixedStock: '0.2', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'โรสแมรี่', fixedStock: '0.01', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เลม่อนนอก', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'หอมหัวใหญ่', fixedStock: '5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เห็ดเข็มทอง', fixedStock: '0.1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เห็ดชิเมจิ', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เห็ดแชมปิยอง', fixedStock: '0.5', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เห็ดหอมสด', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เห็ดหอมแห้ง', fixedStock: '1', unit: 'กก', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เห็ดออรินจิ', fixedStock: '', unit: '', type: 'ผัก-ผลไม้', kitchen: 'ครัวอิตาเลี่ยน' },

    { name: 'Castello Blue Cheese / CA01', fixedStock: ' ', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'Castello JALAPENO HAVARTI', fixedStock: ' ', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'Castello JALAPENO HAVARTI', fixedStock: ' ', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'Grana Padano (Parmesan) 2 กก', fixedStock: '2', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'HARD PAMESAN LATTERIA SORESINA/ DZ06', fixedStock: ' ', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'Parmigiano Reggiano DOP', fixedStock: ' ', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'Pecorino Moliterno', fixedStock: ' ', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'San Paquanburie สันผักหวานบุรี', fixedStock: ' ', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'White Cheedar', fixedStock: ' ', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },    
    { name: 'ขนมปังแถว', fixedStock: '0.5', unit: 'แถว', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ขนมปังฝรั่งเศส', fixedStock: '3', unit: 'แถว', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ข้าวโพดเมล็ด', fixedStock: '24', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'คะนอซุปไก่ก้อน', fixedStock: '2', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'แคปเปอร์เม็ดใหญ่', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ซอสโชวยุ', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ซอสโตเมโตเพลส', fixedStock: '2', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ซอสเทริยากิ', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เต้าหู้ก้อนญี่ปุ่นชนิดเนื้อนิ่ม', fixedStock: '4', unit: 'แพ็ค', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'น้ำผึ้ง เวชพงษ์', fixedStock: '0.5', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'น้ำมันมะกอก Extra', fixedStock: '1', unit: 'กล', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'น้ำมันมะกอก Pomas', fixedStock: '2', unit: 'กล', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'น้ำมันสลัด', fixedStock: '0.5', unit: 'กล', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'น้ำมันเห็ดทรัฟเฟิล', fixedStock: '0.25', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'น้ำส้มแดง (Vinegar)', fixedStock: '0.5', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'น้ำสลัดงา ซีอิ๊วซี่ปุ่น', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เนยจืด อราวลี่', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'บราว์ซอส', fixedStock: '2', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'บาลซามิก', fixedStock: '0.25', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'บูลชีส', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เบคกิ้งโซดา', fixedStock: '1', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ใบลีฟ', fixedStock: '1', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'แป้งพิซซ่า', fixedStock: '1', unit: 'กส', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ปลาโอแห้ง ญี่ปุ่น', fixedStock: '', unit: '', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'แป้งลาซอนย่า', fixedStock: '0.5', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ผงปาปริก้า', fixedStock: '0.25', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'พามาซานชีส', fixedStock: '2', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มอลซาเรราชีส', fixedStock: '5', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มอสน้ำ', fixedStock: '1', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มะกอกเขียวไร้เมล็ด', fixedStock: '6', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มะกอกดำไร้เมล็ด', fixedStock: '12', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มะเขือเทศปอกเปลือก', fixedStock: '12', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มัสตาส ( เม็ด )', fixedStock: '1', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'มัสตาส อโมรา', fixedStock: '3', unit: 'ขวด', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ยีสต์ผง', fixedStock: '1', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เรียวมายองเนส', fixedStock: '6', unit: 'ถุง', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ลูกพีซกระป๋อง', fixedStock: '0.5', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'วิปปิ้งครีม', fixedStock: '6', unit: 'กล่อง', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ไวน์ขาว (ทำอาหาร)', fixedStock: '3', unit: 'ลิตร', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'ไวน์แดง (ทำอาหาร)', fixedStock: '3', unit: 'ลิตร', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'สัปปะรดแว่น', fixedStock: '24', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เส้นเพนนี่', fixedStock: '6', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เส้นเฟสตูชินี่', fixedStock: '10', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เส้นสปาเก็ตตี้ #4', fixedStock: '20', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เส้นสปาเก็ตตี้เส้นดำ', fixedStock: '2', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'เส้นแองเจิ้ลแฮร์', fixedStock: '20', unit: 'ห่อ', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'อัลมอนสไลด์', fixedStock: '0.3', unit: 'กก', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'อารีกาโน', fixedStock: '1', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
    { name: 'อาโรมาต', fixedStock: '3', unit: 'กป', type: 'เครื่องเทศ-ส่วนผสม', kitchen: 'ครัวอิตาเลี่ยน' },
   
    // Bar day
    // เบียร์
    { code: 'เบียร์', name: 'เบียร์', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' }, 
    { code: '', name: 'เบียร์สดไฮเนเก้น 30 L.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'เบียร์สด Hoegarden 20 L.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'เบียร์สด Hoegarden Roee 20 L.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'เบียร์สด Stella Artois 20 L.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'เบียร์สด Budweiser 19.5 L.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: 'S1400', name: 'Corona Extra Beer 355 ml', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '3117', name: 'Chang small', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '2407', name: 'Estrella Damm Inedit', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1448', name: 'Heineken 320 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Heineken 0.0% 330 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1710', name: 'San Mig Light Small 330 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1450', name: 'Singha Small 330 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Thonglor Beer', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1451', name: 'Tiger Small 330 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
 
    // เหล้า
    
    { code: 'เหล้า', name: 'เหล้า', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: 'X1001', name: 'J.W.Black Label (1000 ml)', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1460', name: 'J.W.Black Label (700 ml)', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1489', name: 'Bombay Sapphire Gin 750 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1461', name: 'Chivas 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '14601', name: 'J.W.Gold Label Reserve 750 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '6668', name: 'Grey Goose Vodka 750 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '3102', name: 'Jameson Irish Whiskey 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1462', name: 'Jack Daniel\'s Tennessee Whiskey', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1464', name: 'Jim Beam Kentucky Bourbon Whisky', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '148889', name: 'Jagermeister 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '14888', name: 'Regency 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '14889', name: 'Regency 500 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Regency 350 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1465', name: 'Sangsom 300 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '3101', name: 'J.W. Swing 750 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
   
    // ไวน์

    { code: 'ไวน์', name: 'ไวน์', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '2110', name: 'Wolf Blass-Eaglehawk: Chardonnay', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '2111', name: 'Wolf Blass-Eaglehawk: Merlot', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    
    // เหล้า Malt

    { code: 'เหล้า Malt', name: 'เหล้า Malt', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1484', name: 'Glenfiddich Special Reserve 18 Year', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Glenfiddich Special Reserve 15 Year', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Glenfiddich Special Reserve 12 Year', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Glenlivet 18 Year 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Glenlivet 15 Year 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Glenlivet 12 Year 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Macallan 15 Year Fine Oak 750 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Macallan 12 Year Fine Oak 700 ml.', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
  
    // บาร์รายวัน ทั่วไป

    { code: 'ทั่วไป', name: 'ทั่วไป', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'กระทิงแดง', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1506', name: 'Coke ขวดแก้ว', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Coke กระป๋อง', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1540', name: 'Coke Zero', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1509', name: 'Ginger Ale', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1482', name: 'Red Bull', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1508', name: 'Soda', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1507', name: 'Sprite ขวดแก้ว', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'Sprite กระป๋อง', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1510', name: 'Tonic Water', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '1519', name: 'Water ขวดแก้ว', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },
    { code: '', name: 'น้ำแร่ทองหล่อ', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวัน' },

    // บาร์รายวันบุหรี่

    { code: '1706', name: 'LM Menthol', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },
    { code: '1705', name: 'LM Red', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },
    { code: '1708', name: 'Marlboro Black 2', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },
    { code: '1701', name: 'Marlboro Red', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },
    { code: '1702', name: 'Marlboro Light', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },
    { code: '1703', name: 'Marlboro Menthol', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },
    { code: '1715', name: 'Marlboro Light 7.1', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },
    { code: '1714', name: 'Marlboro Menthol 7.1', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },
    { code: '1711', name: 'Marlboro Arctic X', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },
    { code: '1704', name: 'Marlboro Purple', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },
    { code: '1721', name: 'Marlboro Vista Sunset X2', received: 0, total: 0, barC: 0, storeC: 0, houseSY: 0, barL: 0, barM: 0, z: 0, office: 0, customerBorrow: 0, kitchen: 'บาร์รายวันบุหรี่' },

    // บาร์รายวันผลไม้สด'

    { name: 'แอปเปิ้ลแดง', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'แอ๊ปเปิ้ลเขียว', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'เสาวรส', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'สัปปะรด', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'แคนตาลูป', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'แตงโม', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'มะนาว', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'น้ำมะนาว', unit: 'ขวด', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'นมสด', unit: 'แกลอน', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'โยเกิร์ต', unit: 'กระปุก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'ส้มคั้น', unit: 'กก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'เลมอน', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'ส้มซัน', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    { name: 'มะพร้าว', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายวันผลไม้สด' },
    
    // Bar Week

    { name: 'หลอดยาวพิเศษ', fixedStock: '9', unit: '', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'หลอดดำ 8 มิล', fixedStock: '16', unit: '', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ขวดแก้วสกกั้ก', fixedStock: '3', unit: 'ขวด', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'เชอรี่แดงติดก้าน', fixedStock: '24', unit: 'ขวด', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'น้ำแอปเปิ้ลกล่องเล็ก', fixedStock: '36', unit: 'กล่อง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'น้ำส้ม', fixedStock: '6', unit: 'กล่อง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'น้ำสับปะรด', fixedStock: '3', unit: 'กล่อง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'น้ำมะเขือเทศ', fixedStock: '24', unit: 'กล่อง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'มะกอกเขียน', fixedStock: '4', unit: 'ขวด', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'น้ำแครนเบอร์รี่', fixedStock: '4', unit: 'ขวด', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'คอฟฟี่เมตร', fixedStock: '2', unit: 'ถุง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ผงโกโก้', fixedStock: '1', unit: 'ถุง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'นมข้นหวาน', fixedStock: '3', unit: 'ถุง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'กาแฟพนักงาน', fixedStock: '2', unit: 'ถุง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ผงชาเขียว', fixedStock: '1', unit: 'ถุง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ชาจีน', fixedStock: '13', unit: 'กล่อง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ชาลิปตัน', fixedStock: '3', unit: 'กล่อง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ชาเอีร์ลเกรย์', fixedStock: '2', unit: 'กล่อง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'น้ำตาลทรายแดง', fixedStock: '2', unit: 'โล', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'น้ำตาลทรายขาว', fixedStock: '10', unit: 'โล', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'น้ำผึ้ง', fixedStock: '19', unit: 'ขวด', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ผ้าเย็น', fixedStock: '30', unit: 'ผืน', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ซอสไก่งวง', fixedStock: '3', unit: 'ขวด', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'กาแฟอโรม่า', fixedStock: '7', unit: 'ถุง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'บัตรฝากเหล้า', fixedStock: '300', unit: 'ใบ', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'สติ๊กเกอร์ติดขวดแก้ว', fixedStock: '325', unit: 'ดวง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'จุกรินเหล้า', fixedStock: '15', unit: 'ชิ้น', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'มะตูมแห้ง', fixedStock: '1.9', unit: 'กก', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'อัญชันแห้ง', fixedStock: '0.4', unit: 'กก', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'อบเชยแห้ง', fixedStock: '2.1', unit: 'กก', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ไอศกรีมวานิลลา', fixedStock: '2.4', unit: 'กก', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ไอศกรีมคุกกี้แอนด์ครีม', fixedStock: '1.4', unit: 'กก', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ไอศกรีมช็อคโกแลต', fixedStock: '1.3', unit: 'กก', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ไอศกรีมสตรอเบอรี่', fixedStock: '3.9', unit: 'กก', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ชาเขียว', fixedStock: '10', unit: 'ซอง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'CROFFLE', fixedStock: '25', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'CHOCOLATELOER', fixedStock: '2', unit: 'ลูก', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'สตรอเบอร์รี่แช่แข็ง', fixedStock: '1', unit: 'ถุง', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'มิตรเบอร์รี่รวม', fixedStock: '00', unit: '', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },
    { name: 'ชาครัวไทย', fixedStock: '00', unit: '', type: 'บาร์', kitchen: 'บาร์รายสัปดาห์' },

    // สต๊อกของแห้ง
    
    { name: 'กระดาษรองทอด', unit: 'แพ็ค', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'กะทิ', unit: 'กล่อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'กาวดักหนู', unit: 'กล่อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เกร็ดขนมปัง', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เกลือป่น ปรุงทิพย์', unit: 'กก', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ข้าวเกรียบมโนรา', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ข้าวหอมมะลิ', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'คนอร์ ซุปก้อน รสไก่', unit: 'กระปุก', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'คนอร์ บราวน์ซอส', unit: 'กระปุก', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'คนอร์ ผงปรุงรสไก่', unit: 'กระปุก', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'คนอร์ อโรมาต', unit: 'กระปุก', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'คาราเมล ไซหรับ', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ช้อน/ส้อมพลาสติก', unit: 'แพ็ค', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสโชวยุ', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสทาบาสโก้', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสเทริยากิ', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสปรุงรสฝาเขียว', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสพริก', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสมะเขือเทศ', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสมะเขือเทศ ขวด', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสมะเขือเทศ ซอง', unit: 'แพ็ค', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสมะเขือเทศเข้มข้น', unit: 'กระป๋อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสลาพาริน ( ซอสไก่งวง)', unit: 'กก', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซอสหอยนางรม', unit: 'แกลอน', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซีอิ๊วขาว', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ซีอิ๊วดำ', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ตะเกียบไม้ไผ่', unit: 'แพ็ค', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เต้าเจี้ยว', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ถุงมือยางไม่แป้ง สีดำ', unit: 'กล่อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ถุงมือยางสีส้ม', unit: 'กล่อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ถุงใส่พิซซ่า', unit: 'แพ็ค', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ถุงหูหิ้วใส 12*20', unit: 'แพ็ค', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ถุงหูหิ้วใส 8*16', unit: 'แพ็ค', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ถุงหูหิ้วใส 9*18', unit: 'แพ็ค', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เทียนอเนกประสงค์', unit: 'กล่อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'นมข้นจืดคาเนชั่น', unit: 'กระป๋อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำกระเทียมดอง', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำแครนเบอรี่', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำจิ้มไก่แม่ประนอม', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำเชื่อม กลิ่นเมเปิ้ล', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำตาลทรายขาว', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำตาลทรายแดง', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำตาลทรายแดงละเอียด', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำปลา', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำผึ้ง', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำพริกเผา ฉั่วฮะเส็ง', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำมันพริกเผา  ฉั่วฮะเส็ง', unit: 'กระป๋อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำยาไฮเตอร์', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำส้ม อสร', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำสลัดงาคั่ว', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'น้ำสลัดซีอิ๊วญี่ปุ่น', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เนื้อปลาโออบแห้ง', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เนื้อสัปปะรด', unit: 'ลัง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เบคกิ้งโซดา', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ใบเบย์', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'แป้งโกกิ', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'แป้งทอดกรอบครัววังทิพย์', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'แป้งลาซานย่า', unit: 'กล่อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ผงชูรส', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ผงซักฟอก', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ผงลาบ', unit: 'กล่อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ผ้าเย็น', unit: 'แพ็ค', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'พริกครัวไทยขาวป่น', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ฟิล์มยืดห่ออาหาร', unit: 'ม้วน', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ไฟแช็ค', unit: 'กล่อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'มะกอกเขียวไร้เมล็ด', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'มะกอกเขียวไส้พริก', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'มะกอกดำไร้เมล็ด', unit: 'กระป๋อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'มัสตาร์ด โฮแกรน', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'มัสตาร์ดดิจอง อโมรา', unit: 'ขวด', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เมล็ดข้าวโพดในน้ำเกลือ', unit: 'ลัง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ยากำจัดปลวก', unit: 'กระป๋อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ยากำจัดยุง', unit: 'กระป๋อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ยีสต์ผง', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เรียวมายองเนส', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ลูกพีชในน้ำเชื่อม', unit: 'กระป๋อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'วุ้นเส้น', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ไวน์ขาว ทำอาหาร', unit: 'ลิตร', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ไวน์แดง ทำอาหาร', unit: 'ลิตร', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'สก๊อตซ์ไบรต์', unit: 'แพ็ค', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'สเปรย์ปรับอากาศ', unit: 'กระป๋อง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'สาหร่ายทะเลแห้ง', unit: 'ถุง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เส้นเพนเน่', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เส้นเฟตตูชินี', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เส้นไวไว', unit: 'ลัง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เส้นสปาเกตตี้', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เส้นสปาเก็ตตี้ดำ', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เส้นหมี่อบแห้ง', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'เส้นแองเจิ้ลแฮร์', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'หอมเจียว', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'ออริกาโน่', unit: 'ห่อ', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'อะลูมิเนียมฟอยล์', unit: 'ม้วน', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'แอลกอฮอล์ (บุฟเฟ่ต์ )', unit: 'ถัง', kitchen: 'ของแห้งรายสัปดาห์' },
    { name: 'แอลกอฮอล์ล้างมือ', unit: 'แกลอน', kitchen: 'ของแห้งรายสัปดาห์' },
   
    //นับกล่องรายสัปดาห์

    { name: 'กล่องเหลี่ยมกระดาษ 1000 ML', unit: 'ชิ้น', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'กล่องเหลี่ยมกระดาษ 1200 ML', unit: 'ชิ้น', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'กล่องเหลี่ยมกระดาษ 1200 ML (โลโก้)', unit: 'ชิ้น', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'กล่องเหลี่ยมกระดาษ 1200 ML (รู)', unit: 'ชิ้น', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'กล่องเหลี่ยมกระดาษ 2100 ML', unit: 'ชิ้น', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'กล่องเหลี่ยมกระดาษเล็ก 460 ML. ( ข้าว )', unit: 'ชิ้น', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'กล่องเหลี่ยมพลาสติก 1000 ML', unit: 'ชุด', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'กล่องเหลี่ยมพลาสติก 650 ML', unit: 'ชุด', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'กล่องพิซซ่า 12 นิ้ว', unit: 'กก', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ฝาถ้วยกระดาษ DEP 5 OZ', unit: 'ชิ้น', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ถ้วยกระดาษ DEP 5 OZ', unit: 'ชิ้น', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ถ้วยน้ำจิ้มกลม 30 ML ( พริก-น้ำปลา)', type:'', unit: 'ชุด', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ถ้วยน้ำจิ้มกลม PP ฝาในตัว 40 ml.', type:'', unit: 'ชิ้น', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ถ้วยน้ำจิ้มกลม PP ฝาในตัว 100 ml.', type:'', unit: 'ชิ้น', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ถุงใส่กล่องพิซซ่า', unit: 'แพ็ค', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ถุงหูหิ้วสีขาว 12*20', unit: 'แพ็ค', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ถุงหูหิ้วสีขาว 8*16', unit: 'แพ็ค', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ถุงหูหิ้วสีขาว 9*18', unit: 'แพ็ค', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ช้อนพลาสติก สีดำ', unit: 'ชิ้น', type:'', kitchen: 'นับกล่องรายสัปดาห์' },
    { name: 'ส้อมพลาสติก สีดำ', unit: 'ชิ้น', type:'', kitchen: 'นับกล่องรายสัปดาห์' }

];
